### ISSUE TITLE
[Bug] Discord won't open after Installing BetterDiscordApp

### ISSUE THREAD

**Issue by Sombez** [rauenzi/BetterDiscordApp#441]
After installing it, Discord stopped opening and got an error message. 

I don't know what caused it, but here's my system specs if it helps.

![](https://i.gyazo.com/1181bc97c40de393b8aecf40ba27fb56.png)

**Comment by knighse** [comment]
This also happens on linux, but when running from the command line I receive:
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Session can only be received when app is ready
    at Object.get [as defaultSession] (electron/js2c/browser_init.js:2831:21)
    at removeCSP (/usr/share/discord/resources/app/index.js:47:22)
    at Object.<anonymous> (/usr/share/discord/resources/app/index.js:57:6)
    at Module._compile (internal/modules/cjs/loader.js:880:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
    at Module.load (internal/modules/cjs/loader.js:735:32)
    at Module._load (internal/modules/cjs/loader.js:648:12)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Object.<anonymous> (electron/js2c/browser_init.js:5806:12)

**Comment by rauenzi** [comment]
Try redownloading the lastest version of the mac installer and reinstalling. Let me know if the issue persists. https://github.com/rauenzi/BBDInstaller
